{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-sql",
    "version": "4.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "4.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-sql-4.0.3.jar",
          "url": "spring-boot-sql-4.0.3.jar",
          "size": 36059,
          "sha512": "27d878a9e3eca03cab46d7242f037c75f2b2bc78c351e8cfe9977150d26468210b6e2eaa826f0a5b3e62ded53ffbea98200c661a662f1ff89ce9342930e6f7f8",
          "sha256": "78a46656f34b3e6d44b3696ab2684f89563befe2f02c1a4d45fe25c5740489ce",
          "sha1": "afe39a694d946d9fc185922fd755e7d3fe197571",
          "md5": "c864964b493589933e1ff4d835fb509d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "4.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-sql-4.0.3.jar",
          "url": "spring-boot-sql-4.0.3.jar",
          "size": 36059,
          "sha512": "27d878a9e3eca03cab46d7242f037c75f2b2bc78c351e8cfe9977150d26468210b6e2eaa826f0a5b3e62ded53ffbea98200c661a662f1ff89ce9342930e6f7f8",
          "sha256": "78a46656f34b3e6d44b3696ab2684f89563befe2f02c1a4d45fe25c5740489ce",
          "sha1": "afe39a694d946d9fc185922fd755e7d3fe197571",
          "md5": "c864964b493589933e1ff4d835fb509d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-sql-4.0.3-javadoc.jar",
          "url": "spring-boot-sql-4.0.3-javadoc.jar",
          "size": 163434,
          "sha512": "aa5776b7f3a3f56fccfce263acaa9e2768bface4a1fbb29f431c031a4b169b85d6cb0f5b37b5ee8d03c179dd085415e2d0514790841553d7c0a9d07f3ebfcb45",
          "sha256": "e9e20bf1805be7234e944deaac6f721c72042d27b916597c5fc5b33df8d9c9c6",
          "sha1": "a6e2dc3608d4b5c36775510281f639550957128f",
          "md5": "7e7f5a7cc5803d68e138ce251d001151"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-sql-4.0.3-sources.jar",
          "url": "spring-boot-sql-4.0.3-sources.jar",
          "size": 30638,
          "sha512": "976c2adc0903460387ece98621fc42cdaf902258a3c505d1a7237d7de272483580f69b4177b246154db691535647406cea09ca37e272fa797164eb6d4c42deac",
          "sha256": "251a2a464b38a2953565f8c09e20c717a269562119d66eaf04b9e6d254cf4f55",
          "sha1": "ad4296a6974d1558ce22d6d4af2750834b76f400",
          "md5": "6967bad1e41b3c6522dbe31c08de0e73"
        }
      ]
    }
  ]
}
