{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-logging",
    "version": "4.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.5.32"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-to-slf4j",
          "version": {
            "requires": "2.25.3"
          }
        },
        {
          "group": "org.slf4j",
          "module": "jul-to-slf4j",
          "version": {
            "requires": "2.0.17"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-logging-4.0.3.jar",
          "url": "spring-boot-starter-logging-4.0.3.jar",
          "size": 4743,
          "sha512": "26f00ad9b7ef808e67af64c9d16bd6fd86b96807929c554daa8baa05c31f8b95c4043253b504541bc085802f6b5d38c476640e3f4b83b48467a42cb3945bb409",
          "sha256": "563ddf46921a94bf4f95e44ed54a760c14f4e866713ea579402b246b63adda02",
          "sha1": "a53f6e8b383c6b5bac002a6ff6cd142f480944c6",
          "md5": "4ac3f735ad9898075f766719a1778c9e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.5.32"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-to-slf4j",
          "version": {
            "requires": "2.25.3"
          }
        },
        {
          "group": "org.slf4j",
          "module": "jul-to-slf4j",
          "version": {
            "requires": "2.0.17"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-logging-4.0.3.jar",
          "url": "spring-boot-starter-logging-4.0.3.jar",
          "size": 4743,
          "sha512": "26f00ad9b7ef808e67af64c9d16bd6fd86b96807929c554daa8baa05c31f8b95c4043253b504541bc085802f6b5d38c476640e3f4b83b48467a42cb3945bb409",
          "sha256": "563ddf46921a94bf4f95e44ed54a760c14f4e866713ea579402b246b63adda02",
          "sha1": "a53f6e8b383c6b5bac002a6ff6cd142f480944c6",
          "md5": "4ac3f735ad9898075f766719a1778c9e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-logging-4.0.3-javadoc.jar",
          "url": "spring-boot-starter-logging-4.0.3-javadoc.jar",
          "size": 4743,
          "sha512": "26f00ad9b7ef808e67af64c9d16bd6fd86b96807929c554daa8baa05c31f8b95c4043253b504541bc085802f6b5d38c476640e3f4b83b48467a42cb3945bb409",
          "sha256": "563ddf46921a94bf4f95e44ed54a760c14f4e866713ea579402b246b63adda02",
          "sha1": "a53f6e8b383c6b5bac002a6ff6cd142f480944c6",
          "md5": "4ac3f735ad9898075f766719a1778c9e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-logging-4.0.3-sources.jar",
          "url": "spring-boot-starter-logging-4.0.3-sources.jar",
          "size": 4743,
          "sha512": "26f00ad9b7ef808e67af64c9d16bd6fd86b96807929c554daa8baa05c31f8b95c4043253b504541bc085802f6b5d38c476640e3f4b83b48467a42cb3945bb409",
          "sha256": "563ddf46921a94bf4f95e44ed54a760c14f4e866713ea579402b246b63adda02",
          "sha1": "a53f6e8b383c6b5bac002a6ff6cd142f480944c6",
          "md5": "4ac3f735ad9898075f766719a1778c9e"
        }
      ]
    }
  ]
}
