{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-aspects",
    "version": "7.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.aspectj",
          "module": "aspectjweaver",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "spring-aspects-7.0.5.jar",
          "url": "spring-aspects-7.0.5.jar",
          "size": 50031,
          "sha512": "cb41ea69f0414b3229cb61e2457f545a8a5b01e1ce9ef3904eb319d6ef78f7352997feac1f5c0d55259ed4136e236eb3cdfdee9781fe59528447f3acede22a56",
          "sha256": "e54afec10d29715b9e0734f0c64a32f950af592351fb09c2b6d0a3beb6f07c31",
          "sha1": "69189ba1f8996e79ae0317d45c6b969893b93e7a",
          "md5": "e7d4617cbd7eb4a46953ca99a0dbb107"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.aspectj",
          "module": "aspectjweaver",
          "version": {
            "requires": "1.9.25"
          },
          "excludes": [
            {
              "group": "org.aspectj",
              "module": "aspectjtools"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-aspects-7.0.5.jar",
          "url": "spring-aspects-7.0.5.jar",
          "size": 50031,
          "sha512": "cb41ea69f0414b3229cb61e2457f545a8a5b01e1ce9ef3904eb319d6ef78f7352997feac1f5c0d55259ed4136e236eb3cdfdee9781fe59528447f3acede22a56",
          "sha256": "e54afec10d29715b9e0734f0c64a32f950af592351fb09c2b6d0a3beb6f07c31",
          "sha1": "69189ba1f8996e79ae0317d45c6b969893b93e7a",
          "md5": "e7d4617cbd7eb4a46953ca99a0dbb107"
        }
      ]
    }
  ]
}
