{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-tomcat-runtime",
    "version": "4.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-tomcat",
          "version": {
            "requires": "4.0.3"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-web-server",
          "version": {
            "requires": "4.0.3"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-core",
          "version": {
            "requires": "11.0.18"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-el",
          "version": {
            "requires": "11.0.18"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-websocket",
          "version": {
            "requires": "11.0.18"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-tomcat-runtime-4.0.3.jar",
          "url": "spring-boot-starter-tomcat-runtime-4.0.3.jar",
          "size": 4745,
          "sha512": "70a43bba893e889af5ad89aa78ed89b3caba6316a94314f37820ecdf5999167d070e4fb3035c55d83bfbd954253c020c143b6d96ccce97447b9743de3bca5703",
          "sha256": "45563249ec5e9b12dba74161b8cded24859d816688df591ad519ab3819927e80",
          "sha1": "f6e949420af2eda6aa89192ffca5eb9f0e7dea6b",
          "md5": "c222d2df3d0bee62e4f476bf5fe040ee"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-tomcat",
          "version": {
            "requires": "4.0.3"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-web-server",
          "version": {
            "requires": "4.0.3"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-core",
          "version": {
            "requires": "11.0.18"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-el",
          "version": {
            "requires": "11.0.18"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-websocket",
          "version": {
            "requires": "11.0.18"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-tomcat-runtime-4.0.3.jar",
          "url": "spring-boot-starter-tomcat-runtime-4.0.3.jar",
          "size": 4745,
          "sha512": "70a43bba893e889af5ad89aa78ed89b3caba6316a94314f37820ecdf5999167d070e4fb3035c55d83bfbd954253c020c143b6d96ccce97447b9743de3bca5703",
          "sha256": "45563249ec5e9b12dba74161b8cded24859d816688df591ad519ab3819927e80",
          "sha1": "f6e949420af2eda6aa89192ffca5eb9f0e7dea6b",
          "md5": "c222d2df3d0bee62e4f476bf5fe040ee"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-tomcat-runtime-4.0.3-javadoc.jar",
          "url": "spring-boot-starter-tomcat-runtime-4.0.3-javadoc.jar",
          "size": 4745,
          "sha512": "70a43bba893e889af5ad89aa78ed89b3caba6316a94314f37820ecdf5999167d070e4fb3035c55d83bfbd954253c020c143b6d96ccce97447b9743de3bca5703",
          "sha256": "45563249ec5e9b12dba74161b8cded24859d816688df591ad519ab3819927e80",
          "sha1": "f6e949420af2eda6aa89192ffca5eb9f0e7dea6b",
          "md5": "c222d2df3d0bee62e4f476bf5fe040ee"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-tomcat-runtime-4.0.3-sources.jar",
          "url": "spring-boot-starter-tomcat-runtime-4.0.3-sources.jar",
          "size": 4745,
          "sha512": "70a43bba893e889af5ad89aa78ed89b3caba6316a94314f37820ecdf5999167d070e4fb3035c55d83bfbd954253c020c143b6d96ccce97447b9743de3bca5703",
          "sha256": "45563249ec5e9b12dba74161b8cded24859d816688df591ad519ab3819927e80",
          "sha1": "f6e949420af2eda6aa89192ffca5eb9f0e7dea6b",
          "md5": "c222d2df3d0bee62e4f476bf5fe040ee"
        }
      ]
    }
  ]
}
