{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-autoconfigure",
    "version": "4.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "4.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-autoconfigure-4.0.3.jar",
          "url": "spring-boot-autoconfigure-4.0.3.jar",
          "size": 370758,
          "sha512": "32e5cc0f21d8e7e1be04f29ae02e934109bc26d6bb997958c74438b772ae1ef730a60af0f4528d8651ed4337e057644370a91a33a1a3bcd5fd63790c3d0ed644",
          "sha256": "0d191ce7e4ddfbc4ee5398dccf540e0d0552cfb62dea7735e01a395b85f30e28",
          "sha1": "22e2d188c24d65ed1ffe97363c61e8246d2ed430",
          "md5": "8bc886d2cb53dc31baba91e7b5bc0751"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "4.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-autoconfigure-4.0.3.jar",
          "url": "spring-boot-autoconfigure-4.0.3.jar",
          "size": 370758,
          "sha512": "32e5cc0f21d8e7e1be04f29ae02e934109bc26d6bb997958c74438b772ae1ef730a60af0f4528d8651ed4337e057644370a91a33a1a3bcd5fd63790c3d0ed644",
          "sha256": "0d191ce7e4ddfbc4ee5398dccf540e0d0552cfb62dea7735e01a395b85f30e28",
          "sha1": "22e2d188c24d65ed1ffe97363c61e8246d2ed430",
          "md5": "8bc886d2cb53dc31baba91e7b5bc0751"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-autoconfigure-4.0.3-javadoc.jar",
          "url": "spring-boot-autoconfigure-4.0.3-javadoc.jar",
          "size": 637222,
          "sha512": "c863998a882bbdbbc161221695603d20c2669e5e1c2e57229f2076b2431d8b479101f76a3d224194b3ddcd01e706e8101b485b37354000b3d71600e14935a178",
          "sha256": "b8784a9e7eeab09a18cbf6d252b83974a61bec210984bfd32fab3e4bfeec81d7",
          "sha1": "c77bcaa16508985af2c056eef932ee46955b173b",
          "md5": "a8b26145bb5818d0cb95e1a85940621b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-autoconfigure-4.0.3-sources.jar",
          "url": "spring-boot-autoconfigure-4.0.3-sources.jar",
          "size": 232688,
          "sha512": "c03f43e4296f1e7e1ed23f5adcf7a2245f86795d9c88541a21ccc7e445d1c4f9884e6f61b309e3c3b1372c8b046bf051d492fe289e20817cb9dd7fe3a82e1c70",
          "sha256": "98323b14ec5aa707897e99f57d92fd89a8cf17aedb9333810f0d786b66b75924",
          "sha1": "a2c1652b0034da08ffd3ddadbba4c525d510e8b4",
          "md5": "ef624753e8032992b859d3b263847234"
        }
      ]
    }
  ]
}
