{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fasterxml.jackson.core",
    "module": "jackson-core",
    "version": "2.20.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.20.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-core-2.20.2.jar",
          "url": "jackson-core-2.20.2.jar",
          "size": 593203,
          "sha512": "935f6ab552b61742177f66834d47925d752b6d00ef1ba1ffa5c99a659fb7df152d0c39e17f70dcb2a4672c47c3e7cdc652ee6080eb10f6c3b20450f94e006f7c",
          "sha256": "61b85a41bbc333e6db3b7724d5a9ff5011ec5f9eb1cee41e622420bc6e0e4131",
          "sha1": "615d3bd6d47b569e93d2ad45423f93ca9b002d73",
          "md5": "ffe52c9fbf3776db1941582da7288f11"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.20.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-core-2.20.2.jar",
          "url": "jackson-core-2.20.2.jar",
          "size": 593203,
          "sha512": "935f6ab552b61742177f66834d47925d752b6d00ef1ba1ffa5c99a659fb7df152d0c39e17f70dcb2a4672c47c3e7cdc652ee6080eb10f6c3b20450f94e006f7c",
          "sha256": "61b85a41bbc333e6db3b7724d5a9ff5011ec5f9eb1cee41e622420bc6e0e4131",
          "sha1": "615d3bd6d47b569e93d2ad45423f93ca9b002d73",
          "md5": "ffe52c9fbf3776db1941582da7288f11"
        }
      ]
    }
  ]
}
