{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-servlet",
    "version": "4.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "4.0.3"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "7.0.5"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-servlet-4.0.3.jar",
          "url": "spring-boot-servlet-4.0.3.jar",
          "size": 47082,
          "sha512": "3c5c3ccb2a4f52ab0fad4e20d5071c8fa73ae58835d40c3fcd42cd75c69c4d7603abf6e93b6e924cd39a00cbdd523e909ea40244dc248ea8d58466eb62e6625c",
          "sha256": "c4fb781672cf0a472f3d5a5b550c41b06ac1be437160760748aa0763e387af69",
          "sha1": "7d435c96323d8fa917be8d70b2c2a001a8794ff4",
          "md5": "2781018dc3fa62b9e748bf17dc582004"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "4.0.3"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "7.0.5"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-servlet-4.0.3.jar",
          "url": "spring-boot-servlet-4.0.3.jar",
          "size": 47082,
          "sha512": "3c5c3ccb2a4f52ab0fad4e20d5071c8fa73ae58835d40c3fcd42cd75c69c4d7603abf6e93b6e924cd39a00cbdd523e909ea40244dc248ea8d58466eb62e6625c",
          "sha256": "c4fb781672cf0a472f3d5a5b550c41b06ac1be437160760748aa0763e387af69",
          "sha1": "7d435c96323d8fa917be8d70b2c2a001a8794ff4",
          "md5": "2781018dc3fa62b9e748bf17dc582004"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-servlet-4.0.3-javadoc.jar",
          "url": "spring-boot-servlet-4.0.3-javadoc.jar",
          "size": 216213,
          "sha512": "89563b4016a31d6c39fb4d778e5b39ffba76d8259607879323f0daf42cd42230da6285359cb610d18c5fb9ad9832a1cdcc8278c84bdab77bb76c57cd8fdd9454",
          "sha256": "67e1e64789732f4be01cebcd808a0ec47d7db4f4580125020accb7340648a534",
          "sha1": "58fa42bab48baf320b156ab4183677d44493b560",
          "md5": "f312aa29c493d9af81dc27a3394789b0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-servlet-4.0.3-sources.jar",
          "url": "spring-boot-servlet-4.0.3-sources.jar",
          "size": 44500,
          "sha512": "6e6aaf776284d03797d404cc85c50750250cafe7e0b390e9597775b9f797333d774eac2fe70e42679578051407db4173c897a45c14f1a2b6dc5099cef6cb4fa1",
          "sha256": "de1be05a3623a0b1cde783429584157fb51b729cd63681a81b26937254bc678c",
          "sha1": "9ecd6701150b75bebe57038916a3cd905d287ba3",
          "md5": "cf9ec869b888ddee52a50e83afb83482"
        }
      ]
    }
  ]
}
