{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-web-server",
    "version": "4.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "4.0.3"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "7.0.5"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-web-server-4.0.3.jar",
          "url": "spring-boot-web-server-4.0.3.jar",
          "size": 169265,
          "sha512": "6bae7dd76a5eb966c5055b69a7bd17792b1a12b98165cdafc280376d324825dcbd5e5f27252cbd021d1f69a2b661bf90602ce34aec932e792d6b888dd7c13764",
          "sha256": "ec086c66112d255a028988c125f5a7ef31547b7f594b111a920b86f4c62b45cf",
          "sha1": "ed321647244629861a510d7df598d28689b2aa36",
          "md5": "dfd2c1275480226d8a262edf5bfe19e2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "4.0.3"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "7.0.5"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-web-server-4.0.3.jar",
          "url": "spring-boot-web-server-4.0.3.jar",
          "size": 169265,
          "sha512": "6bae7dd76a5eb966c5055b69a7bd17792b1a12b98165cdafc280376d324825dcbd5e5f27252cbd021d1f69a2b661bf90602ce34aec932e792d6b888dd7c13764",
          "sha256": "ec086c66112d255a028988c125f5a7ef31547b7f594b111a920b86f4c62b45cf",
          "sha1": "ed321647244629861a510d7df598d28689b2aa36",
          "md5": "dfd2c1275480226d8a262edf5bfe19e2"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-web-server-4.0.3-javadoc.jar",
          "url": "spring-boot-web-server-4.0.3-javadoc.jar",
          "size": 411062,
          "sha512": "035bfde3cbfd08d3b7a1b78d2d02cfa3ac4e62d134f665a42f420c7ccf1591275b8f43e85cd110667dff936b387044536ccac5db6412d1da19e72d6d30080caf",
          "sha256": "3f2140dd927b2c68150f666f3f78d61656fdbc814b59b8d274f0dff7c3712582",
          "sha1": "b2d9eb8882c9ca04184bd5a6a55f607ebe14af23",
          "md5": "c1a4b674444d5bed7453737340c75166"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-web-server-4.0.3-sources.jar",
          "url": "spring-boot-web-server-4.0.3-sources.jar",
          "size": 129322,
          "sha512": "14eb310d87dfea3d5a52fb5907eecee0adb366d5be3d415d253f7c1b01e01af8846e756881bc01a2e8fc6f8b0a95eeca4bb493c1cb667ce389db5186a65c596c",
          "sha256": "094086b07bb0beded5d2c93ccf8a753218f96ca9123eba18719acaea1dec1623",
          "sha1": "a5ab695e5db3d322f7781e0cd29816a69bf256df",
          "md5": "224150d3b94ee75347addc3d94be1d73"
        }
      ]
    }
  ]
}
