{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-jdbc",
    "version": "7.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "7.0.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "7.0.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-tx",
          "version": {
            "requires": "7.0.5"
          }
        }
      ],
      "files": [
        {
          "name": "spring-jdbc-7.0.5.jar",
          "url": "spring-jdbc-7.0.5.jar",
          "size": 480403,
          "sha512": "4eaad79da84d29078e92815e2a6ca7323eda1b5ac4fad60e9fcaa2ce6d50cdc3a597d1e923af7de4693d7444dcecc30da6d1c984b2f06db50f86481898c70376",
          "sha256": "64d1d53a5003adcd91c39678e0d21a73f29a1010463b0bf933dd4d77d3657e25",
          "sha1": "10cc68ecb63975683ceb923c2d07f09565ba5e82",
          "md5": "4bc8ace06eb380f4e73b20d372c4a1a1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "7.0.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "7.0.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-tx",
          "version": {
            "requires": "7.0.5"
          }
        }
      ],
      "files": [
        {
          "name": "spring-jdbc-7.0.5.jar",
          "url": "spring-jdbc-7.0.5.jar",
          "size": 480403,
          "sha512": "4eaad79da84d29078e92815e2a6ca7323eda1b5ac4fad60e9fcaa2ce6d50cdc3a597d1e923af7de4693d7444dcecc30da6d1c984b2f06db50f86481898c70376",
          "sha256": "64d1d53a5003adcd91c39678e0d21a73f29a1010463b0bf933dd4d77d3657e25",
          "sha1": "10cc68ecb63975683ceb923c2d07f09565ba5e82",
          "md5": "4bc8ace06eb380f4e73b20d372c4a1a1"
        }
      ]
    }
  ]
}
