{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-webmvc",
    "version": "7.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "7.0.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "7.0.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "7.0.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "7.0.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-expression",
          "version": {
            "requires": "7.0.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "7.0.5"
          }
        }
      ],
      "files": [
        {
          "name": "spring-webmvc-7.0.5.jar",
          "url": "spring-webmvc-7.0.5.jar",
          "size": 1104856,
          "sha512": "cb6ddf5825c87612a90255554a6ae1523bef1cf9e18634bddd35af2ae179f00722d6ee03b66fce53395ef962676e4e772951c40ac7dd56f8cd0e513e722330e8",
          "sha256": "6ac46fa400ab17bd900e9de3d4c5b24b41c08885b216c6f222f5fdf7b9c4798d",
          "sha1": "77b2de8c45182565be884a7158845cb3d6f23788",
          "md5": "816eb26c7c808197b28791336c74772d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "7.0.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "7.0.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "7.0.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "7.0.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-expression",
          "version": {
            "requires": "7.0.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "7.0.5"
          }
        }
      ],
      "files": [
        {
          "name": "spring-webmvc-7.0.5.jar",
          "url": "spring-webmvc-7.0.5.jar",
          "size": 1104856,
          "sha512": "cb6ddf5825c87612a90255554a6ae1523bef1cf9e18634bddd35af2ae179f00722d6ee03b66fce53395ef962676e4e772951c40ac7dd56f8cd0e513e722330e8",
          "sha256": "6ac46fa400ab17bd900e9de3d4c5b24b41c08885b216c6f222f5fdf7b9c4798d",
          "sha1": "77b2de8c45182565be884a7158845cb3d6f23788",
          "md5": "816eb26c7c808197b28791336c74772d"
        }
      ]
    }
  ]
}
