{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-web",
    "version": "7.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "7.0.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "7.0.5"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-observation",
          "version": {
            "requires": "1.16.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-web-7.0.5.jar",
          "url": "spring-web-7.0.5.jar",
          "size": 2212709,
          "sha512": "a0fe3a931d29dd986845cfd0e477d94c6d81c57abb818a8276afe1338d69678414f820880171668bdeebce0cac46a612083bdcd0ad6357bb755492a10655073e",
          "sha256": "727900bdbb458ff2395801bd47d183dc7524a6f9a2fcbcdf59a2e04f9ac78df3",
          "sha1": "b2edb5890bb10edcf1ac539b0a4ef1c105fe8db3",
          "md5": "b6da73665db627aa84c9a60724a0917e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "7.0.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "7.0.5"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-observation",
          "version": {
            "requires": "1.16.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-web-7.0.5.jar",
          "url": "spring-web-7.0.5.jar",
          "size": 2212709,
          "sha512": "a0fe3a931d29dd986845cfd0e477d94c6d81c57abb818a8276afe1338d69678414f820880171668bdeebce0cac46a612083bdcd0ad6357bb755492a10655073e",
          "sha256": "727900bdbb458ff2395801bd47d183dc7524a6f9a2fcbcdf59a2e04f9ac78df3",
          "sha1": "b2edb5890bb10edcf1ac539b0a4ef1c105fe8db3",
          "md5": "b6da73665db627aa84c9a60724a0917e"
        }
      ]
    }
  ]
}
