{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-aop",
    "version": "7.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "7.0.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "7.0.5"
          }
        }
      ],
      "files": [
        {
          "name": "spring-aop-7.0.5.jar",
          "url": "spring-aop-7.0.5.jar",
          "size": 426166,
          "sha512": "7435a6a241bf81540340ec510307f643f89170385353e2c0a64392690f7fc6afcb2daa127a765d283a9f22a47d837e24f0b85ecd011facd4a54dd8df87fab059",
          "sha256": "eca1a435da971e0b26557135eac556d1b6b86db7a1a5eca51d61f024bbdd60db",
          "sha1": "647607a091a862fdf1562764a8f41ef962b6c3cc",
          "md5": "095c823896a9a348c7bbc4222433b8f8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "7.0.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "7.0.5"
          }
        }
      ],
      "files": [
        {
          "name": "spring-aop-7.0.5.jar",
          "url": "spring-aop-7.0.5.jar",
          "size": 426166,
          "sha512": "7435a6a241bf81540340ec510307f643f89170385353e2c0a64392690f7fc6afcb2daa127a765d283a9f22a47d837e24f0b85ecd011facd4a54dd8df87fab059",
          "sha256": "eca1a435da971e0b26557135eac556d1b6b86db7a1a5eca51d61f024bbdd60db",
          "sha1": "647607a091a862fdf1562764a8f41ef962b6c3cc",
          "md5": "095c823896a9a348c7bbc4222433b8f8"
        }
      ]
    }
  ]
}
