{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-tomcat",
    "version": "4.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "4.0.3"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-tomcat-runtime",
          "version": {
            "requires": "4.0.3"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-tomcat",
          "version": {
            "requires": "4.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-tomcat-4.0.3.jar",
          "url": "spring-boot-starter-tomcat-4.0.3.jar",
          "size": 4764,
          "sha512": "ee380681172ac12a23b0025f325918a45c621eebd8f454f7f7c8fb26fb51c706d22f77bf7f5ef9c1dc1c50e65239c8201eb80127d332f32dc1528f70afa305dc",
          "sha256": "2ce99a97c53274a2d959cfed8355a97c099a1a13034df978bf3d275bc6028665",
          "sha1": "458c27ddeb83ee9cb7a022ac8abbc3563167161e",
          "md5": "3eb1abec5412cca299684dd8f70aba44"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "4.0.3"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-tomcat-runtime",
          "version": {
            "requires": "4.0.3"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-tomcat",
          "version": {
            "requires": "4.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-tomcat-4.0.3.jar",
          "url": "spring-boot-starter-tomcat-4.0.3.jar",
          "size": 4764,
          "sha512": "ee380681172ac12a23b0025f325918a45c621eebd8f454f7f7c8fb26fb51c706d22f77bf7f5ef9c1dc1c50e65239c8201eb80127d332f32dc1528f70afa305dc",
          "sha256": "2ce99a97c53274a2d959cfed8355a97c099a1a13034df978bf3d275bc6028665",
          "sha1": "458c27ddeb83ee9cb7a022ac8abbc3563167161e",
          "md5": "3eb1abec5412cca299684dd8f70aba44"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-tomcat-4.0.3-javadoc.jar",
          "url": "spring-boot-starter-tomcat-4.0.3-javadoc.jar",
          "size": 4764,
          "sha512": "ee380681172ac12a23b0025f325918a45c621eebd8f454f7f7c8fb26fb51c706d22f77bf7f5ef9c1dc1c50e65239c8201eb80127d332f32dc1528f70afa305dc",
          "sha256": "2ce99a97c53274a2d959cfed8355a97c099a1a13034df978bf3d275bc6028665",
          "sha1": "458c27ddeb83ee9cb7a022ac8abbc3563167161e",
          "md5": "3eb1abec5412cca299684dd8f70aba44"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-tomcat-4.0.3-sources.jar",
          "url": "spring-boot-starter-tomcat-4.0.3-sources.jar",
          "size": 4764,
          "sha512": "ee380681172ac12a23b0025f325918a45c621eebd8f454f7f7c8fb26fb51c706d22f77bf7f5ef9c1dc1c50e65239c8201eb80127d332f32dc1528f70afa305dc",
          "sha256": "2ce99a97c53274a2d959cfed8355a97c099a1a13034df978bf3d275bc6028665",
          "sha1": "458c27ddeb83ee9cb7a022ac8abbc3563167161e",
          "md5": "3eb1abec5412cca299684dd8f70aba44"
        }
      ]
    }
  ]
}
