{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-http-converter",
    "version": "4.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "4.0.3"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "7.0.5"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-http-converter-4.0.3.jar",
          "url": "spring-boot-http-converter-4.0.3.jar",
          "size": 54313,
          "sha512": "1c89111761d309a1719ffd7c1443fbaf3cdb87ef371dd6f9020326c56780cb2ceddb69457ef78c6b0e57a9ce33c07838524173c7835edf8034115e403bc11bd5",
          "sha256": "a9f3a01605b5432a20a5bb0a959c5ca3097fd1852e494d5ac685800a81846fed",
          "sha1": "072a29a59c5b1b55a151e851c3c823f01bfca106",
          "md5": "8521092ed556cd6eef4cb43e54e2f1f5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "4.0.3"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "7.0.5"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-http-converter-4.0.3.jar",
          "url": "spring-boot-http-converter-4.0.3.jar",
          "size": 54313,
          "sha512": "1c89111761d309a1719ffd7c1443fbaf3cdb87ef371dd6f9020326c56780cb2ceddb69457ef78c6b0e57a9ce33c07838524173c7835edf8034115e403bc11bd5",
          "sha256": "a9f3a01605b5432a20a5bb0a959c5ca3097fd1852e494d5ac685800a81846fed",
          "sha1": "072a29a59c5b1b55a151e851c3c823f01bfca106",
          "md5": "8521092ed556cd6eef4cb43e54e2f1f5"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-http-converter-4.0.3-javadoc.jar",
          "url": "spring-boot-http-converter-4.0.3-javadoc.jar",
          "size": 125627,
          "sha512": "499e3ee9ca79331b37ba27f49dfe189313fcd6a65439298e10dd831cfee2c81abe55e4f0a6c695ff50622bf76c8a47ecfc07b9311f49bd5b71dfdb8df366a164",
          "sha256": "aed53a7ea2bdced10fad613976258b246f3eaf13d4e84e522a9e13cd5eb000b9",
          "sha1": "ee7494d9b09d8fb0bc057379dc096f3da5f720f1",
          "md5": "0a04b2ba16ee08f3d9bb76b5ccb9aa05"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-http-converter-4.0.3-sources.jar",
          "url": "spring-boot-http-converter-4.0.3-sources.jar",
          "size": 25042,
          "sha512": "32b46525af8987b7644665bff8729bab7ac2a9569772d32ddbdf81fdbfe4843458f746148b12d73c3d7c6168a2ed3815d19379ef0bb00c12f2c9c97a8497d861",
          "sha256": "9fd85d7499f23b99e10fc83edb8a7dcdca0e4bca6bc400a93d557d36bba9a2df",
          "sha1": "a282e4d8daddd6c9f98a369bf005e110bac025e8",
          "md5": "2b8ca344f896decb198ac7ea24ab2890"
        }
      ]
    }
  ]
}
