{
  "formatVersion": "1.1",
  "component": {
    "group": "tools.jackson.core",
    "module": "jackson-core",
    "version": "3.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "tools.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "3.0.4"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-core-3.0.4.jar",
          "url": "jackson-core-3.0.4.jar",
          "size": 594174,
          "sha512": "cef46ff477337f2e41c6556e39d17bc11fc92da1704dbd7eccf10842a53d22014c018bfc0ba3119a26242fac178634faf68a6092adfc9b0b6159fbf5c70fe97c",
          "sha256": "e07428df3c608f90a39f030d14755cea514b944e8148b2f95c9521e082c6959b",
          "sha1": "c5be0f5814e161030c29fc48b92c27331729ab7f",
          "md5": "db56f120ad3d1bff047bf6390db7ed16"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "tools.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "3.0.4"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-core-3.0.4.jar",
          "url": "jackson-core-3.0.4.jar",
          "size": 594174,
          "sha512": "cef46ff477337f2e41c6556e39d17bc11fc92da1704dbd7eccf10842a53d22014c018bfc0ba3119a26242fac178634faf68a6092adfc9b0b6159fbf5c70fe97c",
          "sha256": "e07428df3c608f90a39f030d14755cea514b944e8148b2f95c9521e082c6959b",
          "sha1": "c5be0f5814e161030c29fc48b92c27331729ab7f",
          "md5": "db56f120ad3d1bff047bf6390db7ed16"
        }
      ]
    }
  ]
}
