{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-webmvc",
    "version": "4.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-servlet",
          "version": {
            "requires": "4.0.3"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "7.0.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-webmvc",
          "version": {
            "requires": "7.0.5"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-webmvc-4.0.3.jar",
          "url": "spring-boot-webmvc-4.0.3.jar",
          "size": 172793,
          "sha512": "f010605772a9f6e8c64081c45581b57950d6e6a9e31c9da78ba6d04ea708db8375770e9df9ea26237dba83a31c8e029872b096a87df97771a61213fc0624b0ec",
          "sha256": "1d9c97bcc3406750acc3c0a4ccd5ace9e22e0bd3f33e67c7325014116865130d",
          "sha1": "8100d8a8c357271d8d78ecdee0d8441b00243786",
          "md5": "5e280f84a4b80bcc53e45c50ba6da316"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-http-converter",
          "version": {
            "requires": "4.0.3"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-servlet",
          "version": {
            "requires": "4.0.3"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "7.0.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-webmvc",
          "version": {
            "requires": "7.0.5"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-webmvc-4.0.3.jar",
          "url": "spring-boot-webmvc-4.0.3.jar",
          "size": 172793,
          "sha512": "f010605772a9f6e8c64081c45581b57950d6e6a9e31c9da78ba6d04ea708db8375770e9df9ea26237dba83a31c8e029872b096a87df97771a61213fc0624b0ec",
          "sha256": "1d9c97bcc3406750acc3c0a4ccd5ace9e22e0bd3f33e67c7325014116865130d",
          "sha1": "8100d8a8c357271d8d78ecdee0d8441b00243786",
          "md5": "5e280f84a4b80bcc53e45c50ba6da316"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-webmvc-4.0.3-javadoc.jar",
          "url": "spring-boot-webmvc-4.0.3-javadoc.jar",
          "size": 301439,
          "sha512": "4de8c188628a6f6be05ded0168b22d3aa563e88c7182ffbc538ab4106620ec5e078543fcda83ba4b0ec637e0381956d9b8565e5c51b0499b3aec2756930844a5",
          "sha256": "3fb009d0317c5d59edea96026e06af9bc231094a179e1cf305b7b82320322ef0",
          "sha1": "4cc51079dda7c936051140de9d411d78599c79bf",
          "md5": "aacd5623fc2180b9f8112a923b93648b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-webmvc-4.0.3-sources.jar",
          "url": "spring-boot-webmvc-4.0.3-sources.jar",
          "size": 89092,
          "sha512": "89c1a3e25a4a5450814195040a443c57da1b26bb2939a935892cc608de3ea2b013379749b4cdac56ad0158edb40832e26642cf6d32b6a8a23aafe4c53aabaecb",
          "sha256": "c16844c52489d07d5f2c1e7ee0d0e7762ecbe0cb01009b65df5aba7ef1cd2d2e",
          "sha1": "be2ef3a1e0133f31eaf6d14cb471b4a7fb496e8d",
          "md5": "8d926c8d2b0076763b46c1f6adc81c60"
        }
      ]
    }
  ]
}
