{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-core",
    "version": "7.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "commons-logging",
          "module": "commons-logging",
          "version": {
            "requires": "1.3.5"
          }
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "spring-core-7.0.5.jar",
          "url": "spring-core-7.0.5.jar",
          "size": 2024842,
          "sha512": "8f0e18b85e65f58c37e171a77e2183009d30ffb5c3cad64e425bbbd1adffdb245540b994411046f5f084b379ce84498285f9f9b56ce3dd981605a8058c440044",
          "sha256": "768c7a3333dda332028b20ad925c2fdd3c89efad7a1daab65eb2beb762e3bc3e",
          "sha1": "186a59c9647b6a87e9c5ca8a862b8ac478e9ea14",
          "md5": "986d6797bc2c5d4bd647382041290cc8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "commons-logging",
          "module": "commons-logging",
          "version": {
            "requires": "1.3.5"
          }
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "spring-core-7.0.5.jar",
          "url": "spring-core-7.0.5.jar",
          "size": 2024842,
          "sha512": "8f0e18b85e65f58c37e171a77e2183009d30ffb5c3cad64e425bbbd1adffdb245540b994411046f5f084b379ce84498285f9f9b56ce3dd981605a8058c440044",
          "sha256": "768c7a3333dda332028b20ad925c2fdd3c89efad7a1daab65eb2beb762e3bc3e",
          "sha1": "186a59c9647b6a87e9c5ca8a862b8ac478e9ea14",
          "md5": "986d6797bc2c5d4bd647382041290cc8"
        }
      ]
    }
  ]
}
