{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-data-jpa",
    "version": "4.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-data-commons",
          "version": {
            "requires": "4.0.3"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-hibernate",
          "version": {
            "requires": "4.0.3"
          }
        },
        {
          "group": "org.springframework.data",
          "module": "spring-data-jpa",
          "version": {
            "requires": "4.0.3"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aspects",
          "version": {
            "requires": "7.0.5"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-data-jpa-4.0.3.jar",
          "url": "spring-boot-data-jpa-4.0.3.jar",
          "size": 16425,
          "sha512": "b0fa719b94265fa6d80c29e59a02d1a577ec3dda09913282222697b9dcd880e3ea6cc8d7a7da50ada15772e721c3a9b405c66348ddf964da8ba0b800a62c6e2b",
          "sha256": "faa22c96807767ab69d7a90efa907159365fb13f9429bf9add756336c5a3deca",
          "sha1": "ed3bec355933bfb43f5c26e85999fb26714805b0",
          "md5": "f0372c712faa78c0c977521e33840585"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-data-commons",
          "version": {
            "requires": "4.0.3"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-hibernate",
          "version": {
            "requires": "4.0.3"
          }
        },
        {
          "group": "org.springframework.data",
          "module": "spring-data-jpa",
          "version": {
            "requires": "4.0.3"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aspects",
          "version": {
            "requires": "7.0.5"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-data-jpa-4.0.3.jar",
          "url": "spring-boot-data-jpa-4.0.3.jar",
          "size": 16425,
          "sha512": "b0fa719b94265fa6d80c29e59a02d1a577ec3dda09913282222697b9dcd880e3ea6cc8d7a7da50ada15772e721c3a9b405c66348ddf964da8ba0b800a62c6e2b",
          "sha256": "faa22c96807767ab69d7a90efa907159365fb13f9429bf9add756336c5a3deca",
          "sha1": "ed3bec355933bfb43f5c26e85999fb26714805b0",
          "md5": "f0372c712faa78c0c977521e33840585"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-data-jpa-4.0.3-javadoc.jar",
          "url": "spring-boot-data-jpa-4.0.3-javadoc.jar",
          "size": 106895,
          "sha512": "b038b814936d1414fd23f0d050a453a36119e159d3c2920a65f8e2362d6aacb0a5659704dfeb77a46b14931a6aea9019c377480e7004cedad57a3e17c35e4035",
          "sha256": "d72b19f6059712087be2e7238da634f53b059c01cd2d0aae6c02b50dd2b3ffe5",
          "sha1": "bd777c7abe8aaccaa970f8de2c64d4429b6e6edb",
          "md5": "dffeb3948b245ea3f50c95c5403d73f9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-data-jpa-4.0.3-sources.jar",
          "url": "spring-boot-data-jpa-4.0.3-sources.jar",
          "size": 11296,
          "sha512": "71e9ac02cfba84eeefd3e0672fec32e5e3cf917c9343651cb740ee80879b278b0ec6bc82fe969823026f2deed9fa8d64b2c09cd820beed2b616c34a3cea02dbc",
          "sha256": "d60a9fe1309548855784e6d9feb9dda013dd7ba54a4c6ec308bdab816b79d9a5",
          "sha1": "54a0b9f722c3352b2759136af5461737fccb59fb",
          "md5": "6656e6a137586b606f3ae3114c187e0b"
        }
      ]
    }
  ]
}
