{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-beans",
    "version": "7.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "7.0.5"
          }
        }
      ],
      "files": [
        {
          "name": "spring-beans-7.0.5.jar",
          "url": "spring-beans-7.0.5.jar",
          "size": 928012,
          "sha512": "eca9809c6080caa044e01bb9bc0f1b245edc1539c20797b6a11e532935b9e24032947695cbdf4030d5c720c94adbd5894699105890eea1eb9d91caa11b135cad",
          "sha256": "6179d615d24354ddb7bfa45af86e6947853fde62e26c2198539ebdea0ff3920b",
          "sha1": "e20d1006aca78c2c58f5eb85d58bc60672a3527c",
          "md5": "e784369ca22f735384aa1798d134b215"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "7.0.5"
          }
        }
      ],
      "files": [
        {
          "name": "spring-beans-7.0.5.jar",
          "url": "spring-beans-7.0.5.jar",
          "size": 928012,
          "sha512": "eca9809c6080caa044e01bb9bc0f1b245edc1539c20797b6a11e532935b9e24032947695cbdf4030d5c720c94adbd5894699105890eea1eb9d91caa11b135cad",
          "sha256": "6179d615d24354ddb7bfa45af86e6947853fde62e26c2198539ebdea0ff3920b",
          "sha1": "e20d1006aca78c2c58f5eb85d58bc60672a3527c",
          "md5": "e784369ca22f735384aa1798d134b215"
        }
      ]
    }
  ]
}
