{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-orm",
    "version": "7.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "7.0.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "7.0.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-jdbc",
          "version": {
            "requires": "7.0.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-tx",
          "version": {
            "requires": "7.0.5"
          }
        }
      ],
      "files": [
        {
          "name": "spring-orm-7.0.5.jar",
          "url": "spring-orm-7.0.5.jar",
          "size": 223883,
          "sha512": "614b75f6e718adbaaae4e40116c7758b5b83e54fc81225efe5fbe6590f8d64b6f046aac2a0440b4b0c76605879d7e7f9a03461b5eb3b5715c9cf5986752cf4c9",
          "sha256": "23612b81fefb5045ca0ce6c9001aab9cda0d707fdd4eba03a80199a2f7664e16",
          "sha1": "0bd9d32356ea016214154fe86cc49ec8d8eed854",
          "md5": "7b5b0d1d6d492e5cbbdfea9165aa4972"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "7.0.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "7.0.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-jdbc",
          "version": {
            "requires": "7.0.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-tx",
          "version": {
            "requires": "7.0.5"
          }
        }
      ],
      "files": [
        {
          "name": "spring-orm-7.0.5.jar",
          "url": "spring-orm-7.0.5.jar",
          "size": 223883,
          "sha512": "614b75f6e718adbaaae4e40116c7758b5b83e54fc81225efe5fbe6590f8d64b6f046aac2a0440b4b0c76605879d7e7f9a03461b5eb3b5715c9cf5986752cf4c9",
          "sha256": "23612b81fefb5045ca0ce6c9001aab9cda0d707fdd4eba03a80199a2f7664e16",
          "sha1": "0bd9d32356ea016214154fe86cc49ec8d8eed854",
          "md5": "7b5b0d1d6d492e5cbbdfea9165aa4972"
        }
      ]
    }
  ]
}
