{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-context",
    "version": "7.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "7.0.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "7.0.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "7.0.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-expression",
          "version": {
            "requires": "7.0.5"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-observation",
          "version": {
            "requires": "1.16.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-context-7.0.5.jar",
          "url": "spring-context-7.0.5.jar",
          "size": 1396313,
          "sha512": "d87e63cea0eae295c8c81b00317b9ea56f98e7dac7ec7734aab0def6634fc3c2ea30340e38a21137383069f99d91f18b6f139c73981480c4089081a9ac137c62",
          "sha256": "40cd97a508401b791dd6dd0f5f0a4154d5650ed7a52058bf3dcc1c3df55c32a4",
          "sha1": "f0bed37a25f4880f3e93a9556425394087bdc1e9",
          "md5": "3153ea2e754ce032a42811005104c641"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "7.0.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "7.0.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "7.0.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-expression",
          "version": {
            "requires": "7.0.5"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-observation",
          "version": {
            "requires": "1.16.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-context-7.0.5.jar",
          "url": "spring-context-7.0.5.jar",
          "size": 1396313,
          "sha512": "d87e63cea0eae295c8c81b00317b9ea56f98e7dac7ec7734aab0def6634fc3c2ea30340e38a21137383069f99d91f18b6f139c73981480c4089081a9ac137c62",
          "sha256": "40cd97a508401b791dd6dd0f5f0a4154d5650ed7a52058bf3dcc1c3df55c32a4",
          "sha1": "f0bed37a25f4880f3e93a9556425394087bdc1e9",
          "md5": "3153ea2e754ce032a42811005104c641"
        }
      ]
    }
  ]
}
