{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-data-jpa",
    "version": "4.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "4.0.3"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-jdbc",
          "version": {
            "requires": "4.0.3"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-data-jpa",
          "version": {
            "requires": "4.0.3"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-jdbc",
          "version": {
            "requires": "4.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-data-jpa-4.0.3.jar",
          "url": "spring-boot-starter-data-jpa-4.0.3.jar",
          "size": 4761,
          "sha512": "bc0934a78dd5453b15d759e6cde0d55d66b21d5c85aa52c8655ed95e11c91626e47127a8cdc1ee347f92479932efabbe4f025dbc794932c0a8aa99e2012d9670",
          "sha256": "543f10d67b8a30c968d3a8f7caaf9daee4c311a4162eacf4a08d303ad376bef8",
          "sha1": "3c979e063184e0bf2cde9a7d5c7a66401fee0615",
          "md5": "1a190a83f9f8165268dd7cf88e76657e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "4.0.3"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-jdbc",
          "version": {
            "requires": "4.0.3"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-data-jpa",
          "version": {
            "requires": "4.0.3"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-jdbc",
          "version": {
            "requires": "4.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-data-jpa-4.0.3.jar",
          "url": "spring-boot-starter-data-jpa-4.0.3.jar",
          "size": 4761,
          "sha512": "bc0934a78dd5453b15d759e6cde0d55d66b21d5c85aa52c8655ed95e11c91626e47127a8cdc1ee347f92479932efabbe4f025dbc794932c0a8aa99e2012d9670",
          "sha256": "543f10d67b8a30c968d3a8f7caaf9daee4c311a4162eacf4a08d303ad376bef8",
          "sha1": "3c979e063184e0bf2cde9a7d5c7a66401fee0615",
          "md5": "1a190a83f9f8165268dd7cf88e76657e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-data-jpa-4.0.3-javadoc.jar",
          "url": "spring-boot-starter-data-jpa-4.0.3-javadoc.jar",
          "size": 4761,
          "sha512": "bc0934a78dd5453b15d759e6cde0d55d66b21d5c85aa52c8655ed95e11c91626e47127a8cdc1ee347f92479932efabbe4f025dbc794932c0a8aa99e2012d9670",
          "sha256": "543f10d67b8a30c968d3a8f7caaf9daee4c311a4162eacf4a08d303ad376bef8",
          "sha1": "3c979e063184e0bf2cde9a7d5c7a66401fee0615",
          "md5": "1a190a83f9f8165268dd7cf88e76657e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-data-jpa-4.0.3-sources.jar",
          "url": "spring-boot-starter-data-jpa-4.0.3-sources.jar",
          "size": 4761,
          "sha512": "bc0934a78dd5453b15d759e6cde0d55d66b21d5c85aa52c8655ed95e11c91626e47127a8cdc1ee347f92479932efabbe4f025dbc794932c0a8aa99e2012d9670",
          "sha256": "543f10d67b8a30c968d3a8f7caaf9daee4c311a4162eacf4a08d303ad376bef8",
          "sha1": "3c979e063184e0bf2cde9a7d5c7a66401fee0615",
          "md5": "1a190a83f9f8165268dd7cf88e76657e"
        }
      ]
    }
  ]
}
