{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot",
    "version": "4.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "7.0.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "7.0.5"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-4.0.3.jar",
          "url": "spring-boot-4.0.3.jar",
          "size": 1371358,
          "sha512": "dcf7636e5a6ac123f293e2fcca8e4748ec102e7492a1437d479511a5bf303f988c220d3bd5650925d5eac3af956d851bcd080fc48dc35dcc718b0fc97aa5ff4e",
          "sha256": "a1cafa61ab660f42286e5c690da5fb51b20b3cd8bc08a5f1cf7cb07db1d3e2a1",
          "sha1": "3cdf46caf2392aa752dfb956ee010b1d70fb9acd",
          "md5": "b6076a1eabc37e5601569d2478dab76d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "7.0.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "7.0.5"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-4.0.3.jar",
          "url": "spring-boot-4.0.3.jar",
          "size": 1371358,
          "sha512": "dcf7636e5a6ac123f293e2fcca8e4748ec102e7492a1437d479511a5bf303f988c220d3bd5650925d5eac3af956d851bcd080fc48dc35dcc718b0fc97aa5ff4e",
          "sha256": "a1cafa61ab660f42286e5c690da5fb51b20b3cd8bc08a5f1cf7cb07db1d3e2a1",
          "sha1": "3cdf46caf2392aa752dfb956ee010b1d70fb9acd",
          "md5": "b6076a1eabc37e5601569d2478dab76d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-4.0.3-javadoc.jar",
          "url": "spring-boot-4.0.3-javadoc.jar",
          "size": 1827487,
          "sha512": "ba60f643af742cbf6ab17d1a916808c2324ef72878697dd87259813e263c4903cbbd781c77c391f94d389383d5ec835503714ee4bb36455355ececd2100eeb0c",
          "sha256": "c006b54535b7fcf0fdcba6a2e78c8883263d8450b32efd6be55839ea552f872f",
          "sha1": "3f541b2d9912e8b7a427ee204d364355611f72ed",
          "md5": "6b73ff59a0d9a34d6be032510d7a7505"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-4.0.3-sources.jar",
          "url": "spring-boot-4.0.3-sources.jar",
          "size": 850939,
          "sha512": "f4c82cbd8cbef56a8110046998a1636f95f8faac0cef1fa131366bb381f68f6df1cad7fb0c434e5da937588f163de661dd3c8e2f10a07b82cabd666422b761ef",
          "sha256": "8fd6d4c07a4f598dd672dcb5112c3da1896488efcffbdccfd42021d8761cfb5d",
          "sha1": "a9c14b455f87a839d2263d91b95251e9b9964223",
          "md5": "c5bb4eaa41d7ac60cc5327159a4e47b1"
        }
      ]
    }
  ]
}
