{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-jackson",
    "version": "4.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "4.0.3"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-jackson",
          "version": {
            "requires": "4.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-jackson-4.0.3.jar",
          "url": "spring-boot-starter-jackson-4.0.3.jar",
          "size": 4741,
          "sha512": "848593029d43e24c6e07f00e3c13678d8c74155d75ff193171ca1aa45d6fc73e6ab51dbadcd087350ed2ca36cceed35111b4922543748a200f9f1e489377a83a",
          "sha256": "860cc58754c2cbe68a2df145d664f45334a2195a6b5748cf491df782696eb77c",
          "sha1": "01e02c5c501f5a8559a18d608ca847ae6f240dde",
          "md5": "3bf19d27bb860830c0baedc4cf013996"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "4.0.3"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-jackson",
          "version": {
            "requires": "4.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-jackson-4.0.3.jar",
          "url": "spring-boot-starter-jackson-4.0.3.jar",
          "size": 4741,
          "sha512": "848593029d43e24c6e07f00e3c13678d8c74155d75ff193171ca1aa45d6fc73e6ab51dbadcd087350ed2ca36cceed35111b4922543748a200f9f1e489377a83a",
          "sha256": "860cc58754c2cbe68a2df145d664f45334a2195a6b5748cf491df782696eb77c",
          "sha1": "01e02c5c501f5a8559a18d608ca847ae6f240dde",
          "md5": "3bf19d27bb860830c0baedc4cf013996"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-jackson-4.0.3-javadoc.jar",
          "url": "spring-boot-starter-jackson-4.0.3-javadoc.jar",
          "size": 4741,
          "sha512": "848593029d43e24c6e07f00e3c13678d8c74155d75ff193171ca1aa45d6fc73e6ab51dbadcd087350ed2ca36cceed35111b4922543748a200f9f1e489377a83a",
          "sha256": "860cc58754c2cbe68a2df145d664f45334a2195a6b5748cf491df782696eb77c",
          "sha1": "01e02c5c501f5a8559a18d608ca847ae6f240dde",
          "md5": "3bf19d27bb860830c0baedc4cf013996"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-jackson-4.0.3-sources.jar",
          "url": "spring-boot-starter-jackson-4.0.3-sources.jar",
          "size": 4741,
          "sha512": "848593029d43e24c6e07f00e3c13678d8c74155d75ff193171ca1aa45d6fc73e6ab51dbadcd087350ed2ca36cceed35111b4922543748a200f9f1e489377a83a",
          "sha256": "860cc58754c2cbe68a2df145d664f45334a2195a6b5748cf491df782696eb77c",
          "sha1": "01e02c5c501f5a8559a18d608ca847ae6f240dde",
          "md5": "3bf19d27bb860830c0baedc4cf013996"
        }
      ]
    }
  ]
}
