{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-jpa",
    "version": "4.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-jdbc",
          "version": {
            "requires": "4.0.3"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-transaction",
          "version": {
            "requires": "4.0.3"
          }
        },
        {
          "group": "jakarta.persistence",
          "module": "jakarta.persistence-api",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-orm",
          "version": {
            "requires": "7.0.5"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-jpa-4.0.3.jar",
          "url": "spring-boot-jpa-4.0.3.jar",
          "size": 23916,
          "sha512": "9bea885a7a832fa139a913e5c1287816365ecaca1669760a7b201177b234dddb481bc33dee888a22785eb509828258b836b1b326765db43087e061d4c450bcb9",
          "sha256": "f33bbcd4342939eb72a859da962071987f1d28b5ce5fe0a82c29682ccebd3df2",
          "sha1": "efae2341e25e140f4ccd2bf70337752193c10b8c",
          "md5": "12698228bb67c96ec8aea38eed3f2baa"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-jdbc",
          "version": {
            "requires": "4.0.3"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-transaction",
          "version": {
            "requires": "4.0.3"
          }
        },
        {
          "group": "jakarta.persistence",
          "module": "jakarta.persistence-api",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-orm",
          "version": {
            "requires": "7.0.5"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-jpa-4.0.3.jar",
          "url": "spring-boot-jpa-4.0.3.jar",
          "size": 23916,
          "sha512": "9bea885a7a832fa139a913e5c1287816365ecaca1669760a7b201177b234dddb481bc33dee888a22785eb509828258b836b1b326765db43087e061d4c450bcb9",
          "sha256": "f33bbcd4342939eb72a859da962071987f1d28b5ce5fe0a82c29682ccebd3df2",
          "sha1": "efae2341e25e140f4ccd2bf70337752193c10b8c",
          "md5": "12698228bb67c96ec8aea38eed3f2baa"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-jpa-4.0.3-javadoc.jar",
          "url": "spring-boot-jpa-4.0.3-javadoc.jar",
          "size": 136802,
          "sha512": "6c14e3318b781a026ee51b1d7a0ca37cc10a9c9f2f6325cf13245cde9f9057ed1ff7b7c4a9c72f142153df37a098e11be5981eecbfa0dbb0081ac276019b6e58",
          "sha256": "01eb2287d69c6cb2008dabf8a3ce4d6459920bf477948fd78a09721a75ca77cc",
          "sha1": "909f9fd496b83aaadfa31a7005e1360bfada4311",
          "md5": "9d8ccf75eda913f75ad723df6eab686a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-jpa-4.0.3-sources.jar",
          "url": "spring-boot-jpa-4.0.3-sources.jar",
          "size": 18819,
          "sha512": "abb6d52fc83924092b8897f39e97bcee14584397cbe69ff47a8a8bbcf8dc6f38bb94022ea1a665a82379a69e7ffc261047f02bdaed28f37899267859ce3ea3aa",
          "sha256": "c449bfe62fa3a31c554f93b91cf61b816e08578725b8a1a0b5787031baf1d661",
          "sha1": "7d152a697b90c878f4a1a925527392dee7387cc4",
          "md5": "47475904aaa3dd2554a84c51cffc838b"
        }
      ]
    }
  ]
}
