{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter",
    "version": "4.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-logging",
          "version": {
            "requires": "4.0.3"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "4.0.3"
          }
        },
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.5"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-4.0.3.jar",
          "url": "spring-boot-starter-4.0.3.jar",
          "size": 4768,
          "sha512": "f9ec7eed9021959e6a971645804bfabbaf31792b5b9fda903f91fd518849a4b7ac30d02e94586717228ff31cb9ed942e27692056df10eac1acb1eafe61c90ac2",
          "sha256": "b8ab36a15183a17428fee3e4f62a64da99413198e4324e4ac708cc7669cfbc52",
          "sha1": "4e6cfad940a6f23ca7d1e1cc18c19e8d573830ef",
          "md5": "8efee638623601d4c353c29b77c4b503"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-logging",
          "version": {
            "requires": "4.0.3"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "4.0.3"
          }
        },
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.5"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-4.0.3.jar",
          "url": "spring-boot-starter-4.0.3.jar",
          "size": 4768,
          "sha512": "f9ec7eed9021959e6a971645804bfabbaf31792b5b9fda903f91fd518849a4b7ac30d02e94586717228ff31cb9ed942e27692056df10eac1acb1eafe61c90ac2",
          "sha256": "b8ab36a15183a17428fee3e4f62a64da99413198e4324e4ac708cc7669cfbc52",
          "sha1": "4e6cfad940a6f23ca7d1e1cc18c19e8d573830ef",
          "md5": "8efee638623601d4c353c29b77c4b503"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-4.0.3-javadoc.jar",
          "url": "spring-boot-starter-4.0.3-javadoc.jar",
          "size": 4768,
          "sha512": "f9ec7eed9021959e6a971645804bfabbaf31792b5b9fda903f91fd518849a4b7ac30d02e94586717228ff31cb9ed942e27692056df10eac1acb1eafe61c90ac2",
          "sha256": "b8ab36a15183a17428fee3e4f62a64da99413198e4324e4ac708cc7669cfbc52",
          "sha1": "4e6cfad940a6f23ca7d1e1cc18c19e8d573830ef",
          "md5": "8efee638623601d4c353c29b77c4b503"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-4.0.3-sources.jar",
          "url": "spring-boot-starter-4.0.3-sources.jar",
          "size": 4768,
          "sha512": "f9ec7eed9021959e6a971645804bfabbaf31792b5b9fda903f91fd518849a4b7ac30d02e94586717228ff31cb9ed942e27692056df10eac1acb1eafe61c90ac2",
          "sha256": "b8ab36a15183a17428fee3e4f62a64da99413198e4324e4ac708cc7669cfbc52",
          "sha1": "4e6cfad940a6f23ca7d1e1cc18c19e8d573830ef",
          "md5": "8efee638623601d4c353c29b77c4b503"
        }
      ]
    }
  ]
}
